version: 2
updates:
  - package-ecosystem: "go"
    directory: "/"          
    schedule:
      interval: "daily"      
    ignore:
      - dependency-name: "lodash" 
        versions: ["<4.17.21"]  